import { jsPDF } from 'jspdf';
import { AnalysisResult } from '../types';

export function exportAnalysisAsPdf(result: AnalysisResult): void {
  const doc = new jsPDF();
  const margin = 15;
  let y = 20;

  // Header Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59); // Slate 800
  doc.text('ResumeBoost AI - ATS Analysis Report', margin, y);
  
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text(`Target Role: ${result.targetRole} | Date: ${new Date(result.timestamp).toLocaleDateString()} | File: ${result.fileName}`, margin, y);

  y += 12;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, y, 195, y);

  // Scores Summary Box
  y += 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('Executive Scores', margin, y);

  y += 8;
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, 180, 24, 3, 3, 'F');

  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  
  // ATS Score
  const atsColor = result.atsScore >= 80 ? [22, 163, 74] : result.atsScore >= 60 ? [217, 119, 6] : [220, 38, 38];
  doc.setTextColor(atsColor[0], atsColor[1], atsColor[2]);
  doc.text(`ATS Score: ${result.atsScore}/100`, margin + 10, y + 14);

  doc.setTextColor(30, 41, 59);
  doc.text(`Quality Score: ${result.qualityScore}/100`, margin + 70, y + 14);
  doc.text(`Readability: ${result.readabilityScore}/100`, margin + 130, y + 14);

  // Summary
  y += 32;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text('Executive Summary', margin, y);

  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(result.summary, 180);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 6;

  // Strengths
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(22, 163, 74);
  doc.text('Key Strengths', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  result.strengths.slice(0, 4).forEach(item => {
    doc.text(`• ${item}`, margin + 3, y);
    y += 5;
  });

  // Weaknesses
  y += 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(220, 38, 38);
  doc.text('Areas for Improvement', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  result.weaknesses.slice(0, 4).forEach(item => {
    doc.text(`• ${item}`, margin + 3, y);
    y += 5;
  });

  // Missing Keywords
  y += 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(180, 83, 9);
  doc.text('Missing High-Priority ATS Keywords', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  const kwText = result.missingKeywords.join(', ');
  const kwLines = doc.splitTextToSize(kwText, 180);
  doc.text(kwLines, margin + 3, y);
  y += kwLines.length * 5 + 6;

  // Check if page length exceeded
  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  // Immediate Action Items
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 58, 138);
  doc.text('Immediate Priority Action Plan', margin, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  result.roadmap.immediate.concat(result.roadmap.highPriority.slice(0, 3)).forEach(item => {
    const lines = doc.splitTextToSize(`[ ] ${item}`, 180);
    doc.text(lines, margin + 3, y);
    y += lines.length * 5 + 2;
  });

  // Footer page number
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by ResumeBoost AI — Page ${i} of ${pageCount}`, margin, 287);
  }

  doc.save(`${result.fileName.replace('.pdf', '')}_ATS_Report.pdf`);
}
